server:
  port: 8352
  servlet:
    context-path: /api

spring:
#  redis:
#    host: 42.193.113.7
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/amusementpark?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: amusementpark.model

logging:
  level:
    amusementpark: debug
